//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetTransactionData
    {
        public int Id { get; set; }
        public string txid { get; set; }
        public string confirmations { get; set; }
        public string confidence { get; set; }
        public string senders { get; set; }
        public Nullable<bool> from_green_address { get; set; }
        public string amounts_received { get; set; }
        public string total_amount_sent { get; set; }
        public string amounts_sent { get; set; }
        public string type { get; set; }
        public string propagated_by_nodes { get; set; }
        public string time_point { get; set; }
    }
}
