//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetContract
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string send_address { get; set; }
        public string profit { get; set; }
        public string fee { get; set; }
        public string net_profit { get; set; }
        public Nullable<System.DateTime> contract_time { get; set; }
        public string contract_type { get; set; }
        public string isStarted { get; set; }
        public string description { get; set; }
        public string btc_amount { get; set; }
        public Nullable<System.DateTime> last_paid_time { get; set; }
        public string isVerified { get; set; }
        public string isPurchased { get; set; }
        public string emailSecurity { get; set; }
        public string hashrate { get; set; }
        public string hashpower { get; set; }
        public string powercost { get; set; }
        public string usd_amount { get; set; }
        public string total_profit { get; set; }
        public string total_fee { get; set; }
        public string total_net_profit { get; set; }
        public string hashalgo { get; set; }
        public string hashalgo_prefix { get; set; }
        public Nullable<System.DateTime> expired_date { get; set; }
    }
}
