//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCurPrice
    {
        public int Id { get; set; }
        public string price { get; set; }
        public string price_base { get; set; }
        public string exchange { get; set; }
        public string time_point { get; set; }
    }
}
