//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hashpower_history
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string type { get; set; }
        public string hash_amount { get; set; }
        public string usd_amount { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
    }
}
