//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profit_history
    {
        public int Id { get; set; }
        public string username { get; set; }
        public Nullable<decimal> profit { get; set; }
        public Nullable<decimal> fee { get; set; }
        public string algo { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
    }
}
