//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WalletEntities : DbContext
    {
        public WalletEntities()
            : base("name=WalletEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetWalletData> AspNetWalletDatas { get; set; }
        public virtual DbSet<AspNetTransactionData> AspNetTransactionDatas { get; set; }
        public virtual DbSet<AspNetCurPrice> AspNetCurPrices { get; set; }
        public virtual DbSet<AspNetContract> AspNetContracts { get; set; }
        public virtual DbSet<profit_history> profit_history { get; set; }
        public virtual DbSet<hashpower_history> hashpower_history { get; set; }
    }
}
